language: ruby
rvm:
  - 2.6.3

before_install:
  - gem install bundler

script: — bundle install — jobs=3 — retry=3
  — bundle exec rspec spec/models

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: AKIAUZBSSQFYRCNKFI6W
    secret_access_key: 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
    application: "trello_ror_copy"
    deployment_group: "deploy"
    region: "us-east-1"
