addons:
  postgresql: 9.6

  before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database trello_ror_test;' -U postgres

dist: trusty

language: ruby

rvm:
  - 2.6.3
env:
  - DB=postgresql
  - RAILS_ENV=test

before_script:
  - gem install bundler:2.0.2

script:
  - bundle update --bundler
  - bundle install
  - bundle exec rails db:test:prepare
  - jobs=3
  - retry=3
  - bundle exec rspec spec/models

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: AKIAUZBSSQFYRCNKFI6W
    secret_access_key: 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
    application: "trello_ror_copy"
    deployment_group: "deploy"
    region: "us-east-1"
